spring.config.import=optional:file:./.env[.properties]
telegram.bot.username=${BOT_USERNAME}
telegram.bot.token=${BOT_TOKEN}
notification.url=${NOTIFICATION_URL:http://localhost:8000}
notification.api-key=${SERVICE_API_KEY:change-me}
